import { Oswald, Inter } from 'next/font/google';
import "./globals.css";
import NavBar from "@/components/Navbar/NavBar";
import Footer from '@/components/Footer/Footer';


const oswald = Oswald({
  subsets: ['latin'],
  weight: ['700'],
  variable: '--font-oswald', 
});


const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--font-inter', 
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${oswald.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#222222]">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
